import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, ChevronUp, Clock3, Disc3, FileAudio, ImagePlus, LoaderCircle, Music2, Plus, Save, Search, Trash2, Upload } from 'lucide-react'
import { PersianDateTimePicker } from '../components/PersianDateTimePicker'
import { SongMetadataModal } from '../components/SongMetadataModal'
import { Card, Field, PageHeader, SearchBox, StatusBadge } from '../components/Ui'
import { useToast } from '../components/toastContext'
import { useImageCropper } from '../contexts/ImageCropperContext'
import { ApiError, api, errorMessageFa, jsonBody, queryString, resolveMediaUrl } from '../lib/api'
import { useDebouncedValue } from '../lib/hooks'
import type { Artist, Paginated, Song } from '../lib/types'
import { useRemote } from '../lib/useRemote'
import { useAuth } from '../lib/authContext'
import { can } from '../lib/permissions'

type Taxonomy={id:number;name:string;name_en?:string;parent_genre?:number|null}
type ValidationItem={section:string;message:string;track_id?:number}
type ReleaseValidation={valid:boolean;errors:ValidationItem[];warnings:ValidationItem[];lock_version?:number}
type TrackExtra={isrc:string;version:string;explicit:boolean;publishing_owner:string;preview_start:number}
type ReleaseMeta={release_date:string;original_release_date:string;label:string;label_en:string;p_copyright:string;c_copyright:string;territories:string[];cover_url:string;description:string;description_en:string}
type SharedMeta={language:string;label:string;label_en:string;genre_ids:number[];sub_genre_ids:number[];mood_ids:number[];tag_ids:number[];producers:string[];producers_en:string[];composers:string[];composers_en:string[];lyricists:string[];lyricists_en:string[]}
type Release={id:string;title:string;title_en:string;release_type:'single'|'ep'|'album'|'compilation';previously_released:boolean;primary_artist_id:number;primary_artist?:Artist;status:string;current_step:number;tracks:Song[];track_ids:number[];track_extras:Record<string,TrackExtra>;release_metadata:ReleaseMeta;shared_metadata:SharedMeta;validation:ReleaseValidation;lock_version:number;scheduled_at?:string|null}
type PendingAudio={file:File;title:string;title_en:string}

const releaseTypes=[{value:'single',label:'تک‌آهنگ',hint:'دقیقاً ۱ ترک'},{value:'ep',label:'مینی‌آلبوم (EP)',hint:'۲ تا ۷ ترک'},{value:'album',label:'آلبوم',hint:'حداقل ۲ ترک'},{value:'compilation',label:'مجموعه',hint:'حداقل ۲ ترک'}] as const
const languages=[['fa','فارسی'],['en','انگلیسی'],['ar','عربی'],['tr','ترکی'],['ku','کردی'],['other','سایر']] as const
const territoryOptions=['WORLDWIDE','IR','US','CA','EU','UK','AE','TR'] as const
const split=(v:string)=>v.split(/\r?\n|،|,/).map(x=>x.trim()).filter(Boolean)
const join=(v:unknown)=>Array.isArray(v)?v.join('\n'):''
const inOneHour=()=>new Date(Date.now()+60*60*1000).toISOString()
const todayIso=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())

function TaxonomyPicker({title,items,value,onChange,required=false}:{title:string;items:Taxonomy[];value:number[];onChange:(v:number[])=>void;required?:boolean}){
  const [q,setQ]=useState('');const selected=new Set(value);const filtered=items.filter(x=>!q||`${x.name} ${x.name_en||''}`.toLowerCase().includes(q.toLowerCase()))
  return <div className="release-taxonomy"><div className="release-taxonomy__head"><strong>{title}{required?' *':''}</strong><span>{value.length.toLocaleString('fa-IR')} انتخاب</span></div><label><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`جستجوی ${title}`}/></label><div>{filtered.map(item=><button type="button" key={item.id} className={selected.has(item.id)?'is-selected':''} onClick={()=>onChange(selected.has(item.id)?value.filter(id=>id!==item.id):[...value,item.id])}>{item.name}{item.name_en&&<small>{item.name_en}</small>}</button>)}</div></div>
}

export default function AddReleasePage(){
  const {user}=useAuth();const canEdit=can(user,'release_add.edit'),canPublish=can(user,'release_add.publish')
  const nav=useNavigate(),{releaseId}=useParams(),toast=useToast(),{cropImage}=useImageCropper()
  const [step,setStep]=useState(1);const [busy,setBusy]=useState(false);const [release,setRelease]=useState<Release|null>(null)
  const [artistSearch,setArtistSearch]=useState('');const artistQ=useDebouncedValue(artistSearch);const [artistId,setArtistId]=useState<number|''>('')
  const [featuredSearch,setFeaturedSearch]=useState('');const featuredQ=useDebouncedValue(featuredSearch)
  const artists=useRemote<Paginated<Artist>>('/admin/artists/'+queryString({q:artistQ,page_size:100}))
  const featuredArtists=useRemote<Paginated<Artist>>('/admin/artists/'+queryString({q:featuredQ,page_size:100}))
  const genres=useRemote<Taxonomy[]>('/genres/'),subgenres=useRemote<Taxonomy[]>('/subgenres/'),moods=useRemote<Taxonomy[]>('/moods/'),tags=useRemote<Taxonomy[]>('/tags/')
  const [title,setTitle]=useState(''),[titleEn,setTitleEn]=useState(''),[releaseType,setReleaseType]=useState<Release['release_type']>('single'),[previously,setPreviously]=useState(false)
  const [meta,setMeta]=useState<ReleaseMeta>({release_date:todayIso(),original_release_date:'',label:'',label_en:'',p_copyright:'',c_copyright:'',territories:['WORLDWIDE'],cover_url:'',description:'',description_en:''})
  const [shared,setShared]=useState<SharedMeta>({language:'fa',label:'',label_en:'',genre_ids:[],sub_genre_ids:[],mood_ids:[],tag_ids:[],producers:[],producers_en:[],composers:[],composers_en:[],lyricists:[],lyricists_en:[]})
  const [pending,setPending]=useState<PendingAudio[]>([]);const [existingSearch,setExistingSearch]=useState('');const existingQ=useDebouncedValue(existingSearch)
  const existing=useRemote<Paginated<Song>>(release?'/admin/songs/'+queryString({status:'all',include_drafts:true,artist_id:release.primary_artist_id,q:existingQ,page_size:50}):null)
  const drafts=useRemote<Paginated<Release>>(!releaseId&&!release?'/admin/releases/'+queryString({scope:'admin_created',status:'draft',page_size:8}):null)
  const [selectedTrackId,setSelectedTrackId]=useState<number|null>(null);const selectedTrack=release?.tracks.find(x=>x.id===selectedTrackId)||release?.tracks[0]||null
  const [metadataSong,setMetadataSong]=useState<Song|null>(null);const [scheduleMode,setScheduleMode]=useState<'publish'|'schedule'>('publish');const [scheduledAt,setScheduledAt]=useState(inOneHour());const [validation,setValidation]=useState<ReleaseValidation|null>(null)
  const filteredSubgenres=useMemo(()=>{const g=new Set(shared.genre_ids);return (subgenres.data||[]).filter(x=>!x.parent_genre||g.has(x.parent_genre)||shared.sub_genre_ids.includes(x.id))},[subgenres.data,shared.genre_ids,shared.sub_genre_ids])
  const featuredOptions=useMemo(()=>{const map=new Map<number,{id:number;name:string;artistic_name?:string}>();(featuredArtists.data?.results||[]).forEach(a=>map.set(a.id,a));(selectedTrack?.featured_artists||[]).forEach(a=>map.set(a.id,a));return [...map.values()].filter(a=>a.id!==release?.primary_artist_id)},[featuredArtists.data,selectedTrack,release?.primary_artist_id])
  const trackLimit=releaseType==='single'?1:releaseType==='ep'?7:100

  function absorb(next:Release){setRelease(next);setArtistId(next.primary_artist_id);setTitle(next.title||'');setTitleEn(next.title_en||'');setReleaseType(next.release_type);setPreviously(Boolean(next.previously_released));setMeta(next.release_metadata);setShared(next.shared_metadata);setValidation(next.validation||null);if(!selectedTrackId&&next.tracks[0])setSelectedTrackId(next.tracks[0].id)}
  useEffect(()=>{
    if(!releaseId)return
    let cancelled=false
    setBusy(true)
    void api<Release>(`/admin/releases/${releaseId}/`).then(next=>{
      if(cancelled)return
      if(next.status!=='draft'){toast.show('فقط پیش‌نویس انتشار از این صفحه قابل ویرایش است.','error');nav('/releases');return}
      absorb(next);setStep(Math.max(1,Math.min(5,next.current_step||1)))
    }).catch(err=>{if(!cancelled){toast.show(errorMessageFa(err),'error');nav('/releases')}}).finally(()=>{if(!cancelled)setBusy(false)})
    return()=>{cancelled=true}
  },[releaseId])
  async function createDraft(){if(!canEdit)return
    if(!artistId){toast.show('هنرمند اصلی را انتخاب کنید.','error');return}if(!title.trim()){toast.show('عنوان فارسی انتشار الزامی است.','error');return}
    setBusy(true);try{const next=await api<Release>('/admin/releases/',{method:'POST',body:jsonBody({artist_id:artistId,title,title_en:titleEn,release_type:releaseType,previously_released:previously,release_metadata:meta,shared_metadata:shared})});absorb(next);setStep(2);nav(`/releases/add/${next.id}`,{replace:true});toast.show('پیش‌نویس انتشار ساخته شد.','success')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}
  }
  async function patchRelease(extra:Record<string,unknown>={},quiet=false){if(!canEdit)return null;
    if(!release)return null
    const body={lock_version:release.lock_version,title,title_en:titleEn,release_type:releaseType,previously_released:previously,release_metadata:meta,shared_metadata:shared,track_extras:release.track_extras,current_step:step,...extra}
    try{const next=await api<Release>(`/admin/releases/${release.id}/`,{method:'PATCH',body:jsonBody(body)});absorb(next);if(!quiet)toast.show('تغییرات انتشار ذخیره شد.','success');return next}catch(err){toast.show(errorMessageFa(err),'error');return null}
  }
  async function go(next:number){if(!release){if(next>1)await createDraft();return}setBusy(true);const saved=await patchRelease({current_step:next},true);setBusy(false);if(saved)setStep(Math.max(1,Math.min(5,next)))}
  async function uploadCover(file?:File){if(!canEdit)return;if(!file||!release)return;const crop=await cropImage(file,{mode:'square',title:'برش مربعی کاور انتشار',description:'همان برش‌گر پنل هنرمند؛ خروجی باید کاملاً مربعی باشد.',maxOutputBytes:9.5*1024*1024,maxOutputDimension:3000});if(!crop)return;const form=new FormData();form.set('cover_image',crop.file);form.set('lock_version',String(release.lock_version));setBusy(true);try{absorb(await api<Release>(`/admin/releases/${release.id}/artwork/`,{method:'POST',body:form}));toast.show('کاور انتشار بارگذاری شد.','success')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  function pickAudio(files:FileList|null){if(!files)return;const room=Math.max(0,trackLimit-(release?.tracks.length||0));const list=Array.from(files).slice(0,room).filter(f=>/\.(mp3|wav)$/i.test(f.name)).map(f=>({file:f,title:releaseType==='single'?title:f.name.replace(/\.[^.]+$/,''),title_en:releaseType==='single'?titleEn:''}));setPending(list);if(room===0)toast.show(releaseType==='ep'?'مینی‌آلبوم حداکثر ۷ ترک می‌پذیرد.':'ظرفیت ترک‌های این انتشار تکمیل است.','error')}
  async function uploadPending(){if(!canEdit)return;if(!release||!pending.length)return;setBusy(true);try{let current=release;for(const item of pending){if(!item.title.trim()&&!item.title_en.trim())throw new Error('برای همه فایل‌ها عنوان ترک وارد کنید.');const form=new FormData();form.set('audio_file',item.file);form.set('title',item.title);form.set('title_en',item.title_en);form.set('language',shared.language||'fa');form.set('lock_version',String(current.lock_version));current=await api<Release>(`/admin/releases/${release.id}/tracks/upload/`,{method:'POST',body:form})}absorb(current);setPending([]);toast.show('فایل‌های صوتی به انتشار اضافه شدند.','success')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  async function addExisting(songId:number){if(!canEdit)return;if(!release)return;setBusy(true);try{const next=await api<Release>(`/admin/releases/${release.id}/tracks/`,{method:'POST',body:jsonBody({action:'add',song_ids:[songId],lock_version:release.lock_version})});absorb(next);toast.show('ضبط موجود به انتشار اضافه شد.','success')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  async function removeTrack(songId:number){if(!canEdit)return;if(!release)return;setBusy(true);try{absorb(await api<Release>(`/admin/releases/${release.id}/tracks/`,{method:'DELETE',body:jsonBody({song_ids:[songId],lock_version:release.lock_version})}));toast.show('ترک از پیش‌نویس جدا شد.','success')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  async function moveTrack(songId:number,direction:-1|1){if(!canEdit)return;if(!release)return;const ids=release.tracks.map(x=>x.id);const index=ids.indexOf(songId),target=index+direction;if(index<0||target<0||target>=ids.length)return;[ids[index],ids[target]]=[ids[target],ids[index]];setBusy(true);try{absorb(await api<Release>(`/admin/releases/${release.id}/tracks/`,{method:'POST',body:jsonBody({action:'reorder',ordered_song_ids:ids,lock_version:release.lock_version})}))}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  async function saveExtras(trackId:number,patch:Partial<TrackExtra>){if(!canEdit)return;if(!release)return;const current=release.track_extras[String(trackId)]||{isrc:'',version:'',explicit:false,publishing_owner:'',preview_start:0};setBusy(true);const next=await patchRelease({track_extras:{[String(trackId)]:{...current,...patch}}},true);setBusy(false);if(next)toast.show('اطلاعات اختصاصی ترک ذخیره شد.','success')}
  async function updateSongMedia(file?:File){if(!canEdit)return;if(!file||!selectedTrack)return;const crop=await cropImage(file,{mode:'square',title:'برش کاور اختصاصی ترک',maxOutputBytes:9.5*1024*1024,maxOutputDimension:3000});if(!crop)return;const form=new FormData();form.set('cover_image_upload',crop.file);setBusy(true);try{const saved=await api<Song>(`/admin/songs/${selectedTrack.id}/`,{method:'PATCH',body:form});setRelease(r=>r?{...r,tracks:r.tracks.map(t=>t.id===saved.id?saved:t)}:r);toast.show('کاور اختصاصی ترک ذخیره شد.','success')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  async function updateFeatured(ids:number[]){if(!canEdit)return;if(!selectedTrack)return;const form=new FormData();if(ids.length)ids.forEach(id=>form.append('featured_artist_ids',String(id)));else form.append('featured_artist_ids','');setBusy(true);try{const saved=await api<Song>(`/admin/songs/${selectedTrack.id}/`,{method:'PATCH',body:form});setRelease(r=>r?{...r,tracks:r.tracks.map(t=>t.id===saved.id?saved:t)}:r);toast.show('هنرمندان مهمان ذخیره شدند.','success')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  async function validate(){if(!release)return null;setBusy(true);const saved=await patchRelease({current_step:5},true);if(!saved){setBusy(false);return null}try{const result=await api<ReleaseValidation>(`/admin/releases/${release.id}/validate/`,{method:'POST',body:jsonBody({lock_version:saved.lock_version})});setValidation(result);setRelease(r=>r?{...r,validation:result}:r);return result}catch(err){toast.show(errorMessageFa(err),'error');return null}finally{setBusy(false)}}
  async function finish(){if(!canPublish)return;if(!release)return;const result=await validate();if(!result?.valid){toast.show('قبل از انتشار، خطاهای الزامی را برطرف کنید.','error');return}setBusy(true);try{const lockVersion=result.lock_version;await api(`/admin/releases/${release.id}/action/`,{method:'POST',body:jsonBody(scheduleMode==='publish'?{action:'publish',lock_version:lockVersion}:{action:'schedule',scheduled_at:scheduledAt,lock_version:lockVersion})});toast.show(scheduleMode==='publish'?'انتشار با موفقیت منتشر شد.':'انتشار با زمان دقیق انتخاب‌شده زمان‌بندی شد.','success');nav('/releases')}catch(err){if(err instanceof ApiError&&err.body&&typeof err.body==='object'){const serverValidation=(err.body as {validation?:ReleaseValidation}).validation;if(serverValidation){setValidation(serverValidation);setRelease(r=>r?{...r,validation:serverValidation}:r)}}toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}

  async function saveAndClose(){
    if(!release)return
    setBusy(true)
    const saved=await patchRelease({current_step:5},true)
    setBusy(false)
    if(!saved)return
    setRelease(null);setValidation(null);setStep(1);setSelectedTrackId(null)
    nav('/releases/add',{replace:true})
    toast.show('پیش‌نویس ذخیره شد.','success')
  }

  const cover=resolveMediaUrl(meta.cover_url);const extra=selectedTrack&&release?.track_extras[String(selectedTrack.id)]
  return <div className="page-stack release-create-page">
    <PageHeader title="افزودن انتشار" description={canPublish?'ساخت، تکمیل و انتشار آثار از طرف مدیریت':'ساخت و تکمیل پیش‌نویس انتشار از طرف مدیریت'} actions={release?<div className="release-draft-state"><StatusBadge value={release.status}/><span>پیش‌نویس #{release.id.slice(0,8)}</span></div>:undefined}/>
    {!release&&Boolean(drafts.data?.results?.length)&&<Card className="release-form-card"><div className="form-section-title"><strong>پیش‌نویس‌های ناتمام</strong><span>برای ادامه، یکی از پیش‌نویس‌های قبلی را باز کنید.</span></div><div className="release-draft-list">{drafts.data!.results.map(item=><button type="button" key={item.id} className="button button--ghost" onClick={()=>nav(`/releases/add/${item.id}`)}><span>{item.title}</span><small>{item.primary_artist?.artistic_name||item.primary_artist?.name||'—'}</small><ArrowLeft size={16}/></button>)}</div></Card>}
    <Card className="release-stepper">{['هنرمند و نوع','کاور و ترک‌ها','جزئیات ترک','متادیتای مشترک',canPublish?'بررسی و انتشار':'بررسی نهایی'].map((label,i)=><button key={label} type="button" disabled={!release&&i>0} className={step===i+1?'is-active':step>i+1?'is-done':''} onClick={()=>release&&void go(i+1)}><b>{step>i+1?'✓':i+1}</b><span>{label}</span></button>)}</Card>

    {step===1&&<Card className="release-form-card"><div className="form-section-title"><strong>اطلاعات الزامی</strong><span>برای ساخت پیش‌نویس فقط این بخش لازم است؛ حساب کاربری هنرمند نقشی ندارد.</span></div><div className="form-grid">
      <div className="form-grid__full"><SearchBox value={artistSearch} onChange={setArtistSearch} placeholder="جستجوی هنرمند اصلی"/><div className="artist-choice-grid">{(artists.data?.results||[]).map(a=><button type="button" key={a.id} className={artistId===a.id?'is-selected':''} disabled={Boolean(release)} onClick={()=>setArtistId(a.id)}><span className="avatar avatar--image">{a.profile_image?<img src={resolveMediaUrl(a.profile_image)} alt=""/>:(a.artistic_name||a.name)?.[0]}</span><span><strong>{a.artistic_name||a.name}</strong><small>{a.name_en||a.artistic_name_en||'—'}</small></span></button>)}</div></div>
      <Field label="عنوان فارسی *"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="عنوان انگلیسی (اختیاری)"><input dir="ltr" value={titleEn} onChange={e=>setTitleEn(e.target.value)}/></Field>
      <div className="form-grid__full release-type-grid">{releaseTypes.map(x=><button type="button" key={x.value} className={releaseType===x.value?'is-selected':''} onClick={()=>setReleaseType(x.value)}><Disc3 size={19}/><strong>{x.label}</strong><span>{x.hint}</span></button>)}</div>
      <label className="release-check form-grid__full"><input type="checkbox" checked={previously} onChange={e=>setPreviously(e.target.checked)}/><span><strong>این اثر قبلاً منتشر شده است</strong><small>در این حالت فقط تاریخ انتشار اصلی الزامی است؛ ISRC برای هر ترک همچنان اختیاری است.</small></span></label>
    </div><div className="release-page-actions"><span/>{release?<button className="button button--primary" onClick={()=>void go(2)}>ادامه <ArrowLeft size={17}/></button>:<button className="button button--primary" disabled={busy} onClick={()=>void createDraft()}>{busy?<LoaderCircle className="spin" size={17}/>:<Plus size={17}/>}ساخت پیش‌نویس و ادامه</button>}</div></Card>}

    {step===2&&release&&<div className="release-layout"><Card className="release-form-card"><div className="form-section-title"><strong>الزامی برای انتشار</strong><span>کاور، تاریخ، قلمرو و تعداد صحیح ترک‌ها قبل از انتشار اعتبارسنجی می‌شوند.</span></div><div className="release-cover-row"><label className="release-cover-upload">{cover?<img src={cover} alt="کاور"/>:<span><ImagePlus size={30}/>کاور مربعی</span>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void uploadCover(e.target.files?.[0])}/><b>انتخاب و برش کاور</b></label><div className="form-grid release-cover-fields"><Field label="تاریخ انتشار *"><input type="date" min={previously?undefined:todayIso()} dir="ltr" value={meta.release_date} onChange={e=>setMeta({...meta,release_date:e.target.value})}/></Field>{previously&&<Field label="تاریخ انتشار اصلی *"><input type="date" dir="ltr" value={meta.original_release_date} onChange={e=>setMeta({...meta,original_release_date:e.target.value})}/></Field>}<div className="form-grid__full"><div className="release-territory-field"><strong>قلمروها *</strong><div>{territoryOptions.map(code=><button type="button" key={code} className={meta.territories.includes(code)?'is-selected':''} onClick={()=>setMeta({...meta,territories:meta.territories.includes(code)?meta.territories.filter(x=>x!==code):[...meta.territories,code]})}>{code}</button>)}</div><small>همان قلمروهای پنل هنرمند؛ حداقل یک مورد باید انتخاب شود.</small></div></div></div></div>
      <div className="form-section-title"><strong>اختیاری</strong><span>برای سرعت بیشتر می‌توانید بعداً هم تکمیل کنید؛ P-line و C-line هشدار کیفی دارند.</span></div><div className="form-grid"><Field label="P-line / مالکیت ضبط"><input value={meta.p_copyright} onChange={e=>setMeta({...meta,p_copyright:e.target.value})}/></Field><Field label="C-line / مالکیت اثر"><input value={meta.c_copyright} onChange={e=>setMeta({...meta,c_copyright:e.target.value})}/></Field><Field label="ناشر فارسی"><input value={meta.label} onChange={e=>setMeta({...meta,label:e.target.value})}/></Field><Field label="ناشر انگلیسی"><input dir="ltr" value={meta.label_en} onChange={e=>setMeta({...meta,label_en:e.target.value})}/></Field><Field label="توضیحات فارسی"><textarea value={meta.description} onChange={e=>setMeta({...meta,description:e.target.value})}/></Field><Field label="توضیحات انگلیسی"><textarea dir="ltr" value={meta.description_en} onChange={e=>setMeta({...meta,description_en:e.target.value})}/></Field></div></Card>
      <Card className="release-form-card"><div className="form-section-title"><strong>ترک‌ها</strong><span>{releaseType==='single'?'تک‌آهنگ دقیقاً یک ترک می‌پذیرد.':'فایل جدید بارگذاری کنید یا ضبط موجود همین هنرمند را اضافه کنید.'}</span></div>
        <label className="release-audio-drop"><Upload size={24}/><strong>انتخاب فایل MP3 / WAV</strong><span>حداکثر ۵۰۰MB برای هر فایل</span><input type="file" multiple={releaseType!=='single'} accept="audio/mpeg,audio/wav,.mp3,.wav" onChange={e=>pickAudio(e.target.files)}/></label>
        {pending.length>0&&<div className="pending-audio-list">{pending.map((p,i)=><div key={`${p.file.name}-${i}`}><FileAudio size={18}/><div><strong>{p.file.name}</strong><input value={p.title} onChange={e=>setPending(x=>x.map((v,j)=>j===i?{...v,title:e.target.value}:v))} placeholder="عنوان فارسی ترک"/><input dir="ltr" value={p.title_en} onChange={e=>setPending(x=>x.map((v,j)=>j===i?{...v,title_en:e.target.value}:v))} placeholder="English track title"/></div><button className="icon-button is-danger" onClick={()=>setPending(x=>x.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>)}<button className="button button--primary" disabled={busy} onClick={()=>void uploadPending()}>بارگذاری {pending.length.toLocaleString('fa-IR')} فایل</button></div>}
        <div className="existing-recordings"><SearchBox value={existingSearch} onChange={setExistingSearch} placeholder="افزودن از ضبط‌های موجود همین هنرمند"/>{(existing.data?.results||[]).filter(s=>s.status!=='deleted'&&!release.track_ids.includes(s.id)).slice(0,8).map(song=><div key={song.id}><span><strong>{song.title}</strong><small>{song.title_en||song.status}</small></span><button className="button button--compact" disabled={busy||release.tracks.length>=trackLimit} onClick={()=>void addExisting(song.id)}><Plus size={14}/>افزودن</button></div>)}</div>
        <div className="release-track-list">{release.tracks.map((track,i)=><div key={track.id}><b>{(i+1).toLocaleString('fa-IR')}</b><span><strong>{track.title}</strong><small>{track.title_en||'بدون عنوان انگلیسی'} · <StatusBadge value={track.status}/></small></span><div><button className="icon-button" disabled={i===0||busy} onClick={()=>void moveTrack(track.id,-1)}><ChevronUp size={16}/></button><button className="icon-button" disabled={i===release.tracks.length-1||busy} onClick={()=>void moveTrack(track.id,1)}><ChevronDown size={16}/></button><button className="icon-button is-danger" disabled={busy} onClick={()=>void removeTrack(track.id)}><Trash2 size={16}/></button></div></div>)}</div>
      </Card></div>}

    {step===3&&release&&<Card className="release-form-card"><div className="form-section-title"><strong>جزئیات هر ترک</strong><span>فیلدهای سریع اینجا هستند؛ «متادیتای کامل» همان ویرایشگر کامل آهنگ را باز می‌کند.</span></div>{release.tracks.length===0?<div className="inline-note inline-note--danger">ابتدا در مرحله قبل حداقل یک ترک اضافه کنید.</div>:<><div className="release-track-tabs">{release.tracks.map((t,i)=><button type="button" key={t.id} className={(selectedTrack?.id===t.id)?'is-active':''} onClick={()=>setSelectedTrackId(t.id)}><b>{i+1}</b><span>{t.title}</span></button>)}</div>{selectedTrack&&<div className="release-track-editor"><div className="release-track-visual"><label>{selectedTrack.cover_image?<img src={resolveMediaUrl(selectedTrack.cover_image)} alt=""/>:<span><Music2 size={28}/></span>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void updateSongMedia(e.target.files?.[0])}/><b>کاور اختصاصی ترک (اختیاری)</b></label><button className="button button--ghost" onClick={()=>setMetadataSong(selectedTrack)}>متادیتای کامل / اختیاری</button></div><div className="release-track-fields">
          <div className="release-track-requirements"><strong>فیلدهای الزامی این ترک</strong><span>عنوان و فایل صوتی در مرحله قبل ثبت شده‌اند. ISRC در همه حالت‌ها اختیاری است. زبان و ژانر مشترک در مرحله بعد ثبت می‌شوند.</span></div>
          <div className="form-section-title form-section-title--compact"><strong>فیلدهای اختیاری و سریع</strong><span>موارد رایج را همین‌جا وارد کنید؛ جزئیات بیشتر از «متادیتای کامل» در دسترس است.</span></div><div className="form-grid">
          <Field label="ISRC (اختیاری)"><input dir="ltr" value={extra?.isrc||''} placeholder="IRABC2600001" onChange={e=>setRelease(r=>r?{...r,track_extras:{...r.track_extras,[String(selectedTrack.id)]:{...(extra||{isrc:'',version:'',explicit:false,publishing_owner:'',preview_start:0}),isrc:e.target.value}}}:r)}/></Field><Field label="نسخه / Version"><input value={extra?.version||''} onChange={e=>setRelease(r=>r?{...r,track_extras:{...r.track_extras,[String(selectedTrack.id)]:{...(extra||{isrc:'',version:'',explicit:false,publishing_owner:'',preview_start:0}),version:e.target.value}}}:r)}/></Field>
          <Field label="مالک حقوق انتشار"><input value={extra?.publishing_owner||''} onChange={e=>setRelease(r=>r?{...r,track_extras:{...r.track_extras,[String(selectedTrack.id)]:{...(extra||{isrc:'',version:'',explicit:false,publishing_owner:'',preview_start:0}),publishing_owner:e.target.value}}}:r)}/></Field><Field label="شروع پیش‌نمایش (ثانیه)"><input type="number" min="0" value={extra?.preview_start||0} onChange={e=>setRelease(r=>r?{...r,track_extras:{...r.track_extras,[String(selectedTrack.id)]:{...(extra||{isrc:'',version:'',explicit:false,publishing_owner:'',preview_start:0}),preview_start:Number(e.target.value)||0}}}:r)}/></Field>
          <label className="release-check"><input type="checkbox" checked={Boolean(extra?.explicit)} onChange={e=>setRelease(r=>r?{...r,track_extras:{...r.track_extras,[String(selectedTrack.id)]:{...(extra||{isrc:'',version:'',explicit:false,publishing_owner:'',preview_start:0}),explicit:e.target.checked}}}:r)}/><span><strong>محتوای Explicit</strong><small>برای محتوای صریح فعال کنید.</small></span></label>
          <Field label="هنرمندان مهمان"><div className="featured-artist-picker"><input value={featuredSearch} onChange={e=>setFeaturedSearch(e.target.value)} placeholder="جستجوی هنرمند مهمان"/><select multiple value={(selectedTrack.featured_artists||[]).map(a=>String(a.id))} onChange={e=>void updateFeatured(Array.from(e.target.selectedOptions).map(o=>Number(o.value)))}>{featuredOptions.map(a=><option key={a.id} value={a.id}>{a.artistic_name||a.name}</option>)}</select><small>برای انتخاب چند هنرمند از Ctrl/Cmd استفاده کنید.</small></div></Field>
          <div className="form-grid__full"><button className="button button--primary" disabled={busy} onClick={()=>void saveExtras(selectedTrack.id,release.track_extras[String(selectedTrack.id)]||extra||{})}><Save size={16}/>ذخیره اطلاعات سریع ترک</button></div>
        </div></div></div>}</>}</Card>}

    {step===4&&release&&<Card className="release-form-card"><div className="form-section-title"><strong>فیلدهای الزامی مشترک</strong><span>این مقادیر به همه ترک‌های انتشار همگام می‌شوند.</span></div><div className="form-grid"><Field label="زبان *"><select value={shared.language} onChange={e=>setShared({...shared,language:e.target.value})}>{languages.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field></div><div className="release-taxonomy-grid"><TaxonomyPicker title="ژانر" required items={genres.data||[]} value={shared.genre_ids} onChange={v=>setShared({...shared,genre_ids:v})}/><TaxonomyPicker title="زیرژانر" items={filteredSubgenres} value={shared.sub_genre_ids} onChange={v=>setShared({...shared,sub_genre_ids:v})}/><TaxonomyPicker title="حال‌وهوا" items={moods.data||[]} value={shared.mood_ids} onChange={v=>setShared({...shared,mood_ids:v})}/><TaxonomyPicker title="برچسب" items={tags.data||[]} value={shared.tag_ids} onChange={v=>setShared({...shared,tag_ids:v})}/></div><div className="form-section-title"><strong>فیلدهای اختیاری</strong><span>برای ورود سریع، هر عامل را در خط جدا یا با ویرگول وارد کنید.</span></div><div className="form-grid"><Field label="ناشر فارسی"><input value={shared.label} onChange={e=>setShared({...shared,label:e.target.value})}/></Field><Field label="ناشر انگلیسی"><input dir="ltr" value={shared.label_en} onChange={e=>setShared({...shared,label_en:e.target.value})}/></Field><Field label="تهیه‌کنندگان فارسی"><textarea value={join(shared.producers)} onChange={e=>setShared({...shared,producers:split(e.target.value)})}/></Field><Field label="Producers"><textarea dir="ltr" value={join(shared.producers_en)} onChange={e=>setShared({...shared,producers_en:split(e.target.value)})}/></Field><Field label="آهنگسازان فارسی"><textarea value={join(shared.composers)} onChange={e=>setShared({...shared,composers:split(e.target.value)})}/></Field><Field label="Composers"><textarea dir="ltr" value={join(shared.composers_en)} onChange={e=>setShared({...shared,composers_en:split(e.target.value)})}/></Field><Field label="ترانه‌سرایان فارسی"><textarea value={join(shared.lyricists)} onChange={e=>setShared({...shared,lyricists:split(e.target.value)})}/></Field><Field label="Lyricists"><textarea dir="ltr" value={join(shared.lyricists_en)} onChange={e=>setShared({...shared,lyricists_en:split(e.target.value)})}/></Field></div></Card>}

    {step===5&&release&&<div className="release-layout"><Card className="release-form-card"><div className="form-section-title"><strong>اعتبارسنجی نهایی</strong><span>پیش از ثبت نهایی، اطلاعات و فایل‌های انتشار بررسی می‌شوند.</span></div><button className="button button--primary" disabled={busy} onClick={()=>void validate()}>{busy?<LoaderCircle className="spin" size={17}/>:<CheckCircle2 size={17}/>}اجرای بررسی نهایی</button>{validation&&<div className="release-validation"><div className={validation.valid?'is-valid':'is-invalid'}>{validation.valid?<CheckCircle2 size={20}/>:<AlertTriangle size={20}/>}<strong>{validation.valid?'انتشار از نظر الزامات آماده است.':'خطاهای الزامی باقی مانده است.'}</strong></div>{validation.errors.map((x,i)=><div className="validation-row is-error" key={`e${i}`}><AlertTriangle size={15}/><span>{x.message}</span></div>)}{validation.warnings.map((x,i)=><div className="validation-row is-warning" key={`w${i}`}><AlertTriangle size={15}/><span>{x.message}</span></div>)}</div>}</Card>{canPublish?<Card className="release-form-card"><div className="form-section-title"><strong>وضعیت نهایی توسط مدیر</strong><span>می‌توانید بلافاصله منتشر کنید یا لحظه دقیق آینده را انتخاب کنید.</span></div><div className="release-final-options"><button type="button" className={scheduleMode==='publish'?'is-selected':''} onClick={()=>setScheduleMode('publish')}><CheckCircle2 size={22}/><strong>انتشار فوری</strong><span>پس از تأیید نهایی، انتشار بلافاصله در پلتفرم فعال می‌شود.</span></button><button type="button" className={scheduleMode==='schedule'?'is-selected':''} onClick={()=>setScheduleMode('schedule')}><Clock3 size={22}/><strong>زمان‌بندی دقیق</strong><span>تاریخ و ساعت رسمی ایران؛ زمان باید در آینده باشد.</span></button></div>{scheduleMode==='schedule'&&<PersianDateTimePicker value={scheduledAt} onChange={setScheduledAt}/>}<button className="button button--primary button--wide" disabled={busy} onClick={()=>void finish()}>{busy?<LoaderCircle className="spin" size={17}/>:scheduleMode==='publish'?<CheckCircle2 size={17}/>:<Clock3 size={17}/>} {scheduleMode==='publish'?'انتشار نهایی':'ثبت زمان‌بندی'}</button></Card>:<Card className="release-form-card"><div className="form-section-title"><strong>پیش‌نویس آماده است</strong><span>پس از تکمیل بررسی، پیش‌نویس برای ادامه کار مدیریت محفوظ می‌ماند.</span></div><button className="button button--primary button--wide" disabled={busy} onClick={()=>void saveAndClose()}><Save size={17}/>ذخیره و پایان</button></Card>}</div>}

    {release&&canEdit&&<div className="release-page-actions"><button className="button button--ghost" disabled={step===1||busy} onClick={()=>void go(Math.max(1,step-1))}><ArrowRight size={17}/>مرحله قبل</button><div><button className="button button--ghost" disabled={busy} onClick={()=>void patchRelease()}><Save size={16}/>ذخیره پیش‌نویس</button>{step<5&&<button className="button button--primary" disabled={busy} onClick={()=>void go(step+1)}>ذخیره و ادامه <ArrowLeft size={17}/></button>}</div></div>}
    <SongMetadataModal song={metadataSong} initialPage={3} onClose={()=>setMetadataSong(null)} onSaved={saved=>{setRelease(r=>r?{...r,tracks:r.tracks.map(t=>t.id===saved.id?saved:t)}:r);return saved}}/>
  </div>
}
