import { useState } from 'react'
import { Disc3, Eye, EyeOff, Pencil, Save, Trash2 } from 'lucide-react'
import { DataTable } from '../components/DataTable'
import { ProductSelect } from '../components/ProductSelect'
import { MarqueeText } from '../components/MarqueeText'
import { Card, Confirm, ErrorState, Field, Modal, PageHeader, Pagination, SearchBox } from '../components/Ui'
import { useToast } from '../components/toastContext'
import { api, errorMessageFa, queryString } from '../lib/api'
import { useDebouncedValue } from '../lib/hooks'
import { dateTimeFa, numberFa } from '../lib/format'
import type { Album, Paginated } from '../lib/types'
import { useRemote } from '../lib/useRemote'
import { mutationFieldsMatch, pageSnapshot, reconcilePaginatedStable, removePaginatedItem, setPaginatedItem, verifyExactEntity } from '../lib/mutationSync'

export default function AlbumsPage(){
  const [search,setSearch]=useState('');const[sort,setSort]=useState('time');const[direction,setDirection]=useState('desc');const[page,setPage]=useState(1);const[selected,setSelected]=useState<Album|null>(null);const[edit,setEdit]=useState<Album|null>(null);const[remove,setRemove]=useState<{album:Album;mode:'soft'|'hard'}|null>(null);const[draft,setDraft]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false)
  const q=useDebouncedValue(search);const toast=useToast();const remote=useRemote<Paginated<Album>>('/admin/albums/'+queryString({q,sort,direction,page,page_size:20}))
  const verifyAlbum=(album:Album,snapshot=pageSnapshot(remote.data,album.id),refreshPage=false,expect?:'soft-delete'|'hard-delete'|'saved')=>{
    void verifyExactEntity<Album>(`/admin/albums/${album.id}/`,{
      found:server=>{remote.setData(current=>setPaginatedItem(current,server,{indexHint:snapshot.index}));setSelected(current=>current?.id===server.id?server:current);setEdit(current=>current?.id===server.id?server:current)},
      missing:()=>{remote.setData(current=>removePaginatedItem(current,album.id));setSelected(current=>current?.id===album.id?null:current);setEdit(current=>current?.id===album.id?null:current)},
    },expect==='hard-delete'?{stopOnMissing:true}:expect==='soft-delete'?{stopWhenFound:server=>Boolean(server.is_removed)}:expect==='saved'?{stopWhenFound:server=>mutationFieldsMatch(server,album,['title','title_en','description','description_en','release_date'])}:{}).then(outcome=>{if(refreshPage&&outcome!=='superseded')void remote.revalidate((current,incoming)=>reconcilePaginatedStable(current,incoming,snapshot.order))})
  }
  async function detail(a:Album){try{setSelected(await api<Album>(`/admin/albums/${a.id}/`))}catch(err){toast.show(errorMessageFa(err),'error')}}
  function openEdit(a:Album){setEdit(a);setDraft({title:a.title||'',title_en:String(a.title_en||''),description:String(a.description||''),description_en:String(a.description_en||''),release_date:String(a.release_date||'')})}
  async function save(){if(!edit)return;const target=edit;const snapshot=pageSnapshot(remote.data,target.id);setBusy(true);const form=new FormData();Object.entries(draft).forEach(([k,v])=>form.set(k,v));try{const response=await api<Album>(`/admin/albums/${target.id}/`,{method:'PATCH',body:form});const updated:Album={...response,...draft};remote.setData(current=>setPaginatedItem(current,updated,{indexHint:snapshot.index}));toast.show('اطلاعات آلبوم ذخیره شد.','success');setEdit(null);verifyAlbum(updated,snapshot,true,'saved')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  async function removeAlbum(){if(!remove)return;const target=remove;const snapshot=pageSnapshot(remote.data,target.album.id);setBusy(true);try{await api(`/admin/albums/${target.album.id}/?mode=${target.mode}`,{method:'DELETE'});toast.show(target.mode==='soft'?'آلبوم و ترک‌های آن بدون حذف اطلاعات از دسترس مخاطبان خارج شدند.':'رکورد آلبوم برای همیشه حذف شد و ترک‌ها به‌صورت مستقل حفظ شدند.','success');if(target.mode==='hard')remote.setData(current=>removePaginatedItem(current,target.album.id));else remote.setData(current=>setPaginatedItem(current,{...target.album,is_removed:true},{indexHint:snapshot.index}));if(selected?.id===target.album.id)setSelected(null);setRemove(null);verifyAlbum(target.album,snapshot,true,target.mode==='hard'?'hard-delete':'soft-delete')}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  return <div className="page-stack"><PageHeader title="مدیریت آلبوم‌ها" description="مرور، ویرایش و مدیریت ساختار آلبوم‌های منتشرشده"/>
  <Card className="toolbar-card"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="عنوان آلبوم یا هنرمند"/><div className="filters"><ProductSelect ariaLabel="مرتب‌سازی آلبوم‌ها" value={`${sort}:${direction}`} onValueChange={value=>{const[s,d]=value.split(':');setSort(s);setDirection(d);setPage(1)}} options={[{value:'time:desc',label:'جدیدترین'},{value:'release:desc',label:'جدیدترین انتشار'},{value:'songs:desc',label:'بیشترین ترک'},{value:'songs:asc',label:'کمترین ترک'}]}/></div></Card>
  <Card>{remote.error?<ErrorState message={remote.error} retry={()=>void remote.reload()}/>:<><DataTable<Album> loading={remote.loading} rows={remote.data?.results||[]} columns={[
    {key:'album',title:'آلبوم',render:a=><div className="media-cell"><span className="media-cover">{a.cover_image?<img src={a.cover_image} alt="" loading="lazy"/>:<Disc3 size={18}/>}</span><div><MarqueeText as="strong" text={a.title}/><MarqueeText text={a.artist_name}/></div></div>},
    {key:'state',title:'وضعیت',render:a=><span className={`status ${a.is_removed?'status--danger':'status--success'}`}>{a.is_removed?'از دسترس خارج':'فعال'}</span>},{key:'songs',title:'تعداد ترک',render:a=>numberFa(a.songs?.length||0)},{key:'release',title:'تاریخ انتشار',render:a=>a.release_date||'—'},{key:'created',title:'ثبت',render:a=>dateTimeFa(a.created_at)},
    {key:'actions',title:'عملیات',render:a=><div className="row-actions"><button className="icon-button" onClick={()=>void detail(a)} title="جزئیات"><Eye size={17}/></button><button className="icon-button" onClick={()=>openEdit(a)} title="ویرایش"><Pencil size={17}/></button>{!a.is_removed&&<button className="icon-button icon-button--warning" onClick={()=>setRemove({album:a,mode:'soft'})} title="حذف امن؛ خارج از دسترس"><EyeOff size={17}/></button>}<button className="icon-button icon-button--danger" onClick={()=>setRemove({album:a,mode:'hard'})} title="حذف دائمی از دیتابیس"><Trash2 size={17}/></button></div>},
  ]}/>{remote.data&&<Pagination count={remote.data.count} page={page} pageSize={20} onPage={setPage}/>}</>}</Card>
  <Modal open={Boolean(selected)} title="جزئیات آلبوم" onClose={()=>setSelected(null)} wide>{selected&&<div><div className="song-detail__head"><span className="media-cover media-cover--xl">{selected.cover_image?<img src={selected.cover_image} alt=""/>:<Disc3 size={26}/>}</span><div className="song-detail__identity"><MarqueeText as="strong" className="song-detail__title" text={selected.title}/><MarqueeText className="song-detail__artist" text={selected.artist_name}/><span className="muted">{numberFa(selected.songs.length)} ترک · {selected.is_removed?'از دسترس خارج':'فعال'}</span></div></div><div className="track-list">{selected.songs.map((s,i)=><div key={s.id}><b>{numberFa(i+1)}</b><div><MarqueeText as="strong" text={s.title}/><MarqueeText text={s.artist_name}/></div><span>{numberFa(s.plays)} پخش</span></div>)}</div><div className="dialog-actions song-detail__actions">{!selected.is_removed&&<button className="button button--ghost button--warning" onClick={()=>setRemove({album:selected,mode:'soft'})}><EyeOff size={16}/>حذف امن</button>}<button className="button button--danger" onClick={()=>setRemove({album:selected,mode:'hard'})}><Trash2 size={16}/>حذف دائمی</button></div></div>}</Modal>
  <Modal open={Boolean(edit)} title="ویرایش آلبوم" onClose={()=>setEdit(null)}>{edit&&<div className="form-grid"><Field label="عنوان"><input value={draft.title||''} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label="معادل انگلیسی عنوان"><input dir="ltr" value={draft.title_en||''} onChange={e=>setDraft({...draft,title_en:e.target.value})}/></Field><Field label="تاریخ انتشار"><input type="date" value={draft.release_date||''} onChange={e=>setDraft({...draft,release_date:e.target.value})}/></Field><Field label="توضیحات"><textarea value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></Field><Field label="معادل انگلیسی توضیحات"><textarea dir="ltr" value={draft.description_en||''} onChange={e=>setDraft({...draft,description_en:e.target.value})}/></Field><div className="dialog-actions form-grid__full"><button className="button button--ghost" onClick={()=>setEdit(null)}>انصراف</button><button className="button button--primary" disabled={busy} onClick={()=>void save()}><Save size={17}/>ذخیره</button></div></div>}</Modal>
  <Confirm open={Boolean(remove)} title={remove?.mode==='soft'?'حذف امن آلبوم':'حذف دائمی آلبوم'} text={remove?.mode==='soft'?'رکورد آلبوم، ترک‌ها، آمار و سوابق مالی حفظ می‌شوند؛ تمام ترک‌های آلبوم فقط از دسترس مخاطبان خارج خواهند شد.':'فقط رکورد آلبوم برای همیشه حذف می‌شود. ترک‌های آن از دیتابیس حذف نمی‌شوند و به‌صورت مستقل حفظ خواهند شد.'} confirmLabel={remove?.mode==='soft'?'خارج کردن از دسترس':'حذف دائمی آلبوم'} danger={remove?.mode==='hard'} busy={busy} onConfirm={()=>void removeAlbum()} onClose={()=>setRemove(null)}/>
  </div>
}
