import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { CalendarClock, Check, ImagePlus, Megaphone, Music2, Pencil, Plus, Search, Trash2, Volume2, X } from 'lucide-react'
import { Card, Confirm, ErrorState, Field, Modal, PageHeader, Pagination, SearchBox, StatusBadge } from '../components/Ui'
import { DataTable } from '../components/DataTable'
import { ProductSelect } from '../components/ProductSelect'
import { PersianDateTimePicker } from '../components/PersianDateTimePicker'
import { MarqueeText } from '../components/MarqueeText'
import { useToast } from '../components/toastContext'
import { api, errorMessageFa, jsonBody, queryString } from '../lib/api'
import { dateTimeFa, dateTimeTehranFa, numberFa } from '../lib/format'
import { useDebouncedValue } from '../lib/hooks'
import type { Paginated, Promotion, Song } from '../lib/types'
import { useRemote } from '../lib/useRemote'
import { useAuth } from '../lib/authContext'
import { can } from '../lib/permissions'
import { mutationFieldsMatch, pageSnapshot, reconcilePaginatedStable, removePaginatedItem, setPaginatedItem, verifyExactEntity } from '../lib/mutationSync'

type Tab = 'promotions' | 'banners' | 'audio'
type Banner = { id:number; title:string; title_en?:string; image?:string|null; navigate_link?:string|null; is_active:boolean; created_at:string; updated_at:string }
type AudioAd = { id:number; title:string; title_en?:string; audio_url?:string|null; image_cover?:string|null; navigate_link?:string|null; duration?:number|null; is_active:boolean; created_at:string; updated_at:string }
type DeleteTarget = { kind:'promotion'|'banner'|'audio'; id:number; title:string } | null

const promotionState = (item:Promotion, nowMs:number) => !item.is_active ? 'disabled' : item.is_running ? 'running' : new Date(item.starts_at).getTime() > nowMs ? 'upcoming' : 'ended'

function TabButton({ active, onClick, icon, children }:{active:boolean;onClick:()=>void;icon:ReactNode;children:ReactNode}) {
  return <button className={active ? 'content-tab is-active' : 'content-tab'} onClick={onClick}>{icon}<span>{children}</span></button>
}

export default function ContentPage() {
  const {user}=useAuth();const canPromotions=can(user,'content.promotions'),canBanners=can(user,'content.banners'),canAudio=can(user,'content.audio_ads')
  const allowedTabs:Tab[]=[...(canPromotions?['promotions' as const]:[]),...(canBanners?['banners' as const]:[]),...(canAudio?['audio' as const]:[])]
  const [tab, setTab] = useState<Tab>(()=>allowedTabs[0]||'promotions')
  useEffect(()=>{if(!allowedTabs.includes(tab)&&allowedTabs[0])setTab(allowedTabs[0])},[canPromotions,canBanners,canAudio])
  return <div className="page-stack">
    <PageHeader title="مدیریت محتوا" description="پروموت آهنگ، بنرها و تبلیغات صوتی" />
    <div className="content-tabs" role="tablist" aria-label="بخش‌های مدیریت محتوا">
      {canPromotions&&<TabButton active={tab==='promotions'} onClick={()=>setTab('promotions')} icon={<Megaphone size={18}/>}>پروموت آهنگ</TabButton>}
      {canBanners&&<TabButton active={tab==='banners'} onClick={()=>setTab('banners')} icon={<ImagePlus size={18}/>}>بنرها</TabButton>}
      {canAudio&&<TabButton active={tab==='audio'} onClick={()=>setTab('audio')} icon={<Volume2 size={18}/>}>تبلیغ صوتی</TabButton>}
    </div>
    {canPromotions&&tab==='promotions' && <PromotionsPanel canManage/>}
    {canBanners&&tab==='banners' && <BannersPanel canManage/>}
    {canAudio&&tab==='audio' && <AudioPanel canManage/>}
  </div>
}

function PromotionsPanel({canManage}:{canManage:boolean}) {
  const toast = useToast()
  const [search,setSearch]=useState(''); const q=useDebouncedValue(search)
  const [state,setState]=useState(''); const [page,setPage]=useState(1)
  const [editing,setEditing]=useState<Promotion|null>(null); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false)
  const [createWindow,setCreateWindow]=useState<{starts:string;ends:string}|null>(null)
  const [clockMs,setClockMs]=useState(()=>Date.now())
  const [deleteTarget,setDeleteTarget]=useState<DeleteTarget>(null)
  const path='/admin/promotions/'+queryString({q,state,page,page_size:20})
  const remote=useRemote<Paginated<Promotion>>(path)
  useEffect(()=>{
    const update=()=>setClockMs(Date.now())
    const initial=window.setTimeout(update,0)
    const interval=window.setInterval(update,60_000)
    return()=>{window.clearTimeout(initial);window.clearInterval(interval)}
  },[])
  const openCreate=()=>{const starts=new Date();const ends=new Date(starts.getTime()+24*60*60*1000);setCreateWindow({starts:starts.toISOString(),ends:ends.toISOString()});setEditing(null);setOpen(true)}
  const openEdit=(item:Promotion)=>{setCreateWindow(null);setEditing(item);setOpen(true)}
  const visiblePromotion=(item:Promotion)=>{const starts=new Date(item.starts_at).getTime();const ends=new Date(item.ends_at).getTime();const stateMatch=!state||(state==='running'&&item.is_active&&starts<=clockMs&&ends>clockMs)||(state==='upcoming'&&item.is_active&&starts>clockMs)||(state==='ended'&&ends<=clockMs)||(state==='disabled'&&!item.is_active);const needle=q.trim().toLocaleLowerCase();const searchMatch=!needle||`${item.song_title||''} ${item.artist_name||''}`.toLocaleLowerCase().includes(needle);return stateMatch&&searchMatch}
  const promotionInsertIndex=(items:Promotion[],item:Promotion)=>{const starts=new Date(item.starts_at).getTime();const index=items.findIndex(current=>{const currentStarts=new Date(current.starts_at).getTime();return currentStarts<starts||(currentStarts===starts&&current.id<item.id)});return index<0?items.length:index}
  const syncPromotion=(item:Promotion,snapshot=pageSnapshot(remote.data,item.id),refreshPage=false,allowInsert=true,expect?:'missing'|'saved')=>{void verifyExactEntity<Promotion>(`/admin/promotions/${item.id}/`,{found:server=>remote.setData(current=>setPaginatedItem(current,server,{visible:visiblePromotion(server)&&(snapshot.index>=0||allowInsert),indexHint:snapshot.index})),missing:()=>remote.setData(current=>removePaginatedItem(current,item.id))},expect==='missing'?{stopOnMissing:true}:expect==='saved'?{stopWhenFound:server=>mutationFieldsMatch(server,item,['song','aggression','starts_at','ends_at','is_active'])}:{}).then(outcome=>{if(refreshPage&&outcome!=='superseded')void remote.revalidate((current,incoming)=>reconcilePaginatedStable(current,incoming,snapshot.order))})}
  async function remove(){if(!deleteTarget)return;const target=deleteTarget;const snapshot=pageSnapshot(remote.data,target.id);setBusy(true);try{await api(`/admin/promotions/${target.id}/`,{method:'DELETE'});remote.setData(current=>removePaginatedItem(current,target.id));toast.show('پروموت حذف شد.','success');setDeleteTarget(null);syncPromotion({id:target.id} as Promotion,snapshot,true,false,'missing')}catch(e){toast.show(errorMessageFa(e),'error')}finally{setBusy(false)}}
  return <>
    <Card className="toolbar-card"><SearchBox value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="نام آهنگ یا هنرمند"/><div className="filters"><ProductSelect ariaLabel="فیلتر وضعیت پروموشن" value={state} onValueChange={value=>{setState(value);setPage(1)}} options={[{value:'',label:'همه وضعیت‌ها'},{value:'running',label:'در حال اجرا'},{value:'upcoming',label:'زمان‌بندی شده'},{value:'ended',label:'پایان یافته'},{value:'disabled',label:'غیرفعال'}]}/>{canManage&&<button className="button button--primary" onClick={openCreate}><Plus size={17}/>پروموت جدید</button>}</div></Card>
    <Card className="promotion-list-card">{remote.error?<ErrorState message={remote.error} retry={()=>void remote.reload()}/>:<><DataTable<Promotion> loading={remote.loading} rows={remote.data?.results||[]} emptyTitle="پروموتی ثبت نشده است" columns={[
      {key:'song',title:'آهنگ',render:x=><div className="media-cell">{x.cover_image?<img src={x.cover_image} alt="" loading="lazy"/>:<div className="media-placeholder"><Music2 size={18}/></div>}<div><MarqueeText as="strong" text={x.song_title}/><MarqueeText text={x.artist_name}/></div></div>},
      {key:'aggression',title:'شدت نمایش',render:x=><div className="aggression-cell"><strong>{numberFa(x.aggression)}</strong><div className="mini-meter"><i style={{width:`${x.aggression}%`}}/></div></div>},
      {key:'window',title:'بازه اجرا',render:x=><div className="stacked-text"><span>{dateTimeTehranFa(x.starts_at)}</span><small>تا {dateTimeTehranFa(x.ends_at)}</small></div>},
      {key:'state',title:'وضعیت',render:x=><StatusBadge value={promotionState(x,clockMs)}/>},
      ...(canManage?[{key:'actions',title:'عملیات',render:(x:Promotion)=><div className="row-actions"><button className="icon-button" aria-label="ویرایش پروموت" onClick={()=>openEdit(x)}><Pencil size={16}/></button><button className="icon-button icon-button--danger" aria-label="حذف پروموت" onClick={()=>setDeleteTarget({kind:'promotion',id:x.id,title:x.song_title})}><Trash2 size={16}/></button></div>}]:[]),
    ]}/>{remote.data&&<Pagination count={remote.data.count} page={page} pageSize={20} onPage={setPage}/>}</>}</Card>
    {canManage&&open&&<PromotionEditor open item={editing} createWindow={createWindow} onClose={()=>setOpen(false)} onSaved={saved=>{const snapshot=pageSnapshot(remote.data,saved.id);const isCreate=snapshot.index<0;const insertIndex=promotionInsertIndex(remote.data?.results||[],saved);const fitsFirstPage=page===1&&((remote.data?.results.length||0)<20||insertIndex<20);const visible=visiblePromotion(saved)&&(!isCreate||fitsFirstPage);const preferred=isCreate&&visible?[...snapshot.order.slice(0,insertIndex),saved.id,...snapshot.order.slice(insertIndex)]:snapshot.order;remote.setData(current=>setPaginatedItem(current,saved,{visible,indexHint:isCreate?insertIndex:snapshot.index}));setEditing(null);setOpen(false);syncPromotion(saved,{...snapshot,order:preferred},true,visible,'saved')}}/>}
    <Confirm open={Boolean(deleteTarget)} title="حذف پروموت" text={`پروموت «${deleteTarget?.title||''}» حذف شود؟`} confirmLabel="حذف" danger busy={busy} onClose={()=>setDeleteTarget(null)} onConfirm={()=>void remove()}/>
  </>
}

function PromotionEditor({open,item,createWindow,onClose,onSaved}:{open:boolean;item:Promotion|null;createWindow:{starts:string;ends:string}|null;onClose:()=>void;onSaved:(saved:Promotion)=>void|Promise<void>}) {
  const toast=useToast(); const [busy,setBusy]=useState(false)
  const [songId,setSongId]=useState<number|null>(item?.song||null); const [songLabel,setSongLabel]=useState(item?`${item.song_title} — ${item.artist_name}`:'')
  const [songSearch,setSongSearch]=useState(''); const dq=useDebouncedValue(songSearch)
  const [aggression,setAggression]=useState(item?.aggression||60); const [starts,setStarts]=useState(item?.starts_at||createWindow?.starts||''); const [ends,setEnds]=useState(item?.ends_at||createWindow?.ends||''); const [active,setActive]=useState(item?.is_active??true)
  const songs=useRemote<Paginated<Song>>(open && !songId && dq.trim().length>=2?'/admin/songs/'+queryString({q:dq,status:'published',page_size:8}):null)
  async function submit(e:FormEvent){e.preventDefault();if(!songId){toast.show('ابتدا یک آهنگ منتشرشده انتخاب کنید.','error');return}if(!starts||!ends||new Date(ends)<=new Date(starts)){toast.show('زمان پایان باید بعد از زمان شروع باشد.','error');return}setBusy(true);try{const body={song:songId,aggression:Number(aggression),starts_at:starts,ends_at:ends,is_active:active};const response=await api<Promotion>(item?`/admin/promotions/${item.id}/`:'/admin/promotions/',{method:item?'PATCH':'POST',body:jsonBody(body)});const saved:Promotion={...response,...body};toast.show(item?'پروموت به‌روزرسانی شد.':'پروموت زمان‌بندی شد.','success');await onSaved(saved)}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
  return <Modal open={open} title={item?'ویرایش پروموت':'پروموت آهنگ'} onClose={onClose} wide><form className="form-grid promotion-form" onSubmit={submit}>
    <div className="form-grid__full"><Field label="آهنگ منتشرشده" hint="فقط آهنگ‌های منتشرشده قابل پروموت هستند.">{songId?<div className="selected-song"><Check size={18}/><strong>{songLabel}</strong><button type="button" className="icon-button icon-button--sm" aria-label="تغییر آهنگ" onClick={()=>{setSongId(null);setSongLabel('')}}><X size={15}/></button></div>:<><label className="search-box search-box--field"><Search size={18}/><input value={songSearch} onChange={e=>setSongSearch(e.target.value)} placeholder="حداقل دو نویسه از نام آهنگ یا هنرمند"/></label>{songs.loading&&<div className="inline-note">در حال جستجوی آهنگ…</div>}{songs.data?.results?.length?<div className="song-picker song-picker--promotion">{songs.data.results.map(song=><button type="button" key={song.id} onClick={()=>{setSongId(song.id);setSongLabel(`${song.title} — ${song.artist_name}`)}}><span className="song-picker__art">{song.cover_image?<img src={song.cover_image} alt="" loading="lazy"/>:<Music2 size={17}/>}</span><span className="song-picker__copy"><strong>{song.title}</strong><small>{song.artist_name}</small></span></button>)}</div>:null}</>}</Field></div>
    <div className="form-grid__full"><Field label={`شدت نمایش: ${numberFa(aggression)} از ۱۰۰`} hint={aggression===100?'در شدت ۱۰۰، آهنگ در تمام مدت پروموت در جایگاه اول پیشنهادها می‌ماند.':undefined}><div className="range-row"><span>کم</span><input className="range" type="range" min="1" max="100" value={aggression} onChange={e=>setAggression(Number(e.target.value))}/><span>زیاد</span><output>{numberFa(aggression)}</output></div></Field></div>
    <Field label="شروع پروموت"><PersianDateTimePicker value={starts} onChange={setStarts} placeholder="تاریخ و ساعت شروع"/></Field>
    <Field label="پایان پروموت"><PersianDateTimePicker value={ends} onChange={setEnds} placeholder="تاریخ و ساعت پایان"/></Field>
    <label className="switch-row form-grid__full"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><span className="switch"/><span><strong>پروموت فعال باشد</strong><small>در صورت غیرفعال بودن، زمان‌بندی نگه داشته می‌شود اما در پیشنهادها اثری ندارد.</small></span></label>
    <div className="dialog-actions form-grid__full"><button type="button" className="button button--ghost" onClick={onClose}>انصراف</button><button className="button button--primary" disabled={busy}><CalendarClock size={17}/>{busy?'در حال ذخیره…':'ذخیره پروموت'}</button></div>
  </form></Modal>
}

function BannersPanel({canManage}:{canManage:boolean}){
  const toast=useToast();const[page,setPage]=useState(1);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Banner|null>(null);const[busy,setBusy]=useState(false);const[del,setDel]=useState<DeleteTarget>(null)
  const remote=useRemote<Paginated<Banner>>('/admin/ads/banners/'+queryString({page,page_size:20}))
  const syncBanner=(item:Banner,snapshot=pageSnapshot(remote.data,item.id),refreshPage=false,allowInsert=true,expect?:'missing'|'saved')=>{void verifyExactEntity<Banner>(`/admin/ads/banners/${item.id}/`,{found:server=>remote.setData(current=>setPaginatedItem(current,server,{visible:snapshot.index>=0||allowInsert,indexHint:snapshot.index})),missing:()=>remote.setData(current=>removePaginatedItem(current,item.id))},expect==='missing'?{stopOnMissing:true}:expect==='saved'?{stopWhenFound:server=>mutationFieldsMatch(server,item,['title','title_en','navigate_link','is_active'])}:{}).then(outcome=>{if(refreshPage&&outcome!=='superseded')void remote.revalidate((current,incoming)=>reconcilePaginatedStable(current,incoming,snapshot.order))})}
  async function remove(){if(!del)return;const target=del;const snapshot=pageSnapshot(remote.data,target.id);setBusy(true);try{await api(`/admin/ads/banners/${target.id}/`,{method:'DELETE'});remote.setData(current=>removePaginatedItem(current,target.id));toast.show('بنر حذف شد.','success');setDel(null);syncBanner({id:target.id} as Banner,snapshot,true,false,'missing')}catch(e){toast.show(errorMessageFa(e),'error')}finally{setBusy(false)}}
  return <><div className="section-actions"><div><strong>بنرهای پلتفرم</strong><span>مدیریت تصویر، لینک مقصد و وضعیت نمایش</span></div>{canManage&&<button className="button button--primary" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/>بنر جدید</button>}</div><Card className="promotion-list-card">{remote.error?<ErrorState message={remote.error} retry={()=>void remote.reload()}/>:<><DataTable<Banner> loading={remote.loading} rows={remote.data?.results||[]} emptyTitle="بنری ثبت نشده است" columns={[
    {key:'banner',title:'بنر',render:x=><div className="media-cell">{x.image?<img src={x.image} alt="" loading="lazy"/>:<div className="media-placeholder"><ImagePlus size={18}/></div>}<div><strong>{x.title}</strong><span>{x.navigate_link||'بدون لینک مقصد'}</span></div></div>},{key:'state',title:'نمایش',render:x=><StatusBadge value={x.is_active?'active':'disabled'}/>},{key:'time',title:'ایجاد',render:x=>dateTimeFa(x.created_at)},...(canManage?[{key:'actions',title:'عملیات',render:(x:Banner)=><div className="row-actions"><button className="icon-button" onClick={()=>{setEditing(x);setOpen(true)}} aria-label="ویرایش بنر"><Pencil size={16}/></button><button className="icon-button icon-button--danger" onClick={()=>setDel({kind:'banner',id:x.id,title:x.title})} aria-label="حذف بنر"><Trash2 size={16}/></button></div>}]:[])
  ]}/>{remote.data&&<Pagination count={remote.data.count} page={page} pageSize={20} onPage={setPage}/>}</>}</Card>{canManage&&open&&<BannerEditor open item={editing} onClose={()=>setOpen(false)} onSaved={saved=>{const snapshot=pageSnapshot(remote.data,saved.id);const isCreate=snapshot.index<0;const visible=!isCreate||page===1;const preferred=isCreate&&visible?[saved.id,...snapshot.order]:snapshot.order;remote.setData(current=>setPaginatedItem(current,saved,{visible,indexHint:isCreate?0:snapshot.index}));setEditing(null);setOpen(false);syncBanner(saved,{...snapshot,order:preferred},true,visible,'saved')}}/>}<Confirm open={Boolean(del)} title="حذف بنر" text={`بنر «${del?.title||''}» حذف شود؟`} confirmLabel="حذف" danger busy={busy} onClose={()=>setDel(null)} onConfirm={()=>void remove()}/></>
}

function BannerEditor({open,item,onClose,onSaved}:{open:boolean;item:Banner|null;onClose:()=>void;onSaved:(saved:Banner)=>void|Promise<void>}){
 const toast=useToast();const[busy,setBusy]=useState(false);const[title,setTitle]=useState(item?.title||'');const[titleEn,setTitleEn]=useState(item?.title_en||'');const[link,setLink]=useState(item?.navigate_link||'');const[active,setActive]=useState(item?.is_active??true);const[file,setFile]=useState<File|null>(null)
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const f=new FormData();f.append('title',title);f.append('title_en',titleEn);f.append('navigate_link',link);f.append('is_active',String(active));if(file)f.append('image_upload',file);const response=await api<Banner>(item?`/admin/ads/banners/${item.id}/`:'/admin/ads/banners/',{method:item?'PATCH':'POST',body:f});const saved:Banner={...response,title,title_en:titleEn,navigate_link:link,is_active:active};toast.show(item?'بنر به‌روزرسانی شد.':'بنر ایجاد شد.','success');await onSaved(saved)}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
 return <Modal open={open} title={item?'ویرایش بنر':'بنر جدید'} onClose={onClose}><form className="form-grid" onSubmit={submit}><Field label="عنوان فارسی"><input value={title} onChange={e=>setTitle(e.target.value)} required/></Field><Field label="عنوان انگلیسی"><input dir="ltr" value={titleEn} onChange={e=>setTitleEn(e.target.value)} required/></Field><div className="form-grid__full"><Field label="لینک مقصد"><input dir="ltr" value={link} onChange={e=>setLink(e.target.value)} placeholder="نشانی مقصد"/></Field></div><div className="form-grid__full"><Field label="تصویر بنر" hint={item?'اگر تصویر جدید انتخاب نکنید، تصویر فعلی حفظ می‌شود.':'یک تصویر بنر انتخاب کنید.'}><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)} required={!item}/></Field></div><label className="switch-row form-grid__full"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><span className="switch"/><span><strong>نمایش بنر فعال باشد</strong></span></label><div className="dialog-actions form-grid__full"><button type="button" className="button button--ghost" onClick={onClose}>انصراف</button><button className="button button--primary" disabled={busy}>{busy?'در حال ذخیره…':'ذخیره بنر'}</button></div></form></Modal>
}


function AudioPanel({canManage}:{canManage:boolean}){
 const toast=useToast();const[page,setPage]=useState(1);const[open,setOpen]=useState(false);const[editing,setEditing]=useState<AudioAd|null>(null);const[busy,setBusy]=useState(false);const[del,setDel]=useState<DeleteTarget>(null)
 const remote=useRemote<Paginated<AudioAd>>('/admin/ads/audio/'+queryString({page,page_size:20}))
 const syncAudio=(item:AudioAd,snapshot=pageSnapshot(remote.data,item.id),refreshPage=false,allowInsert=true,expect?:'missing'|'saved')=>{void verifyExactEntity<AudioAd>(`/admin/ads/audio/${item.id}/`,{found:server=>remote.setData(current=>setPaginatedItem(current,server,{visible:snapshot.index>=0||allowInsert,indexHint:snapshot.index})),missing:()=>remote.setData(current=>removePaginatedItem(current,item.id))},expect==='missing'?{stopOnMissing:true}:expect==='saved'?{stopWhenFound:server=>mutationFieldsMatch(server,item,['title','title_en','navigate_link','is_active'])}:{}).then(outcome=>{if(refreshPage&&outcome!=='superseded')void remote.revalidate((current,incoming)=>reconcilePaginatedStable(current,incoming,snapshot.order))})}
 async function remove(){if(!del)return;const target=del;const snapshot=pageSnapshot(remote.data,target.id);setBusy(true);try{await api(`/admin/ads/audio/${target.id}/`,{method:'DELETE'});remote.setData(current=>removePaginatedItem(current,target.id));toast.show('تبلیغ صوتی حذف شد.','success');setDel(null);syncAudio({id:target.id} as AudioAd,snapshot,true,false,'missing')}catch(e){toast.show(errorMessageFa(e),'error')}finally{setBusy(false)}}
 return <><div className="section-actions"><div><strong>تبلیغات صوتی</strong><span>فایل صوتی، کاور و لینک مقصد</span></div>{canManage&&<button className="button button--primary" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/>تبلیغ جدید</button>}</div><Card className="promotion-list-card">{remote.error?<ErrorState message={remote.error} retry={()=>void remote.reload()}/>:<><DataTable<AudioAd> loading={remote.loading} rows={remote.data?.results||[]} emptyTitle="تبلیغ صوتی ثبت نشده است" columns={[
 {key:'name',title:'تبلیغ',render:x=><div className="media-cell">{x.image_cover?<img src={x.image_cover} alt="" loading="lazy"/>:<div className="media-placeholder"><Volume2 size={18}/></div>}<div><strong>{x.title}</strong><span>{x.duration?`${numberFa(x.duration)} ثانیه`:'مدت نامشخص'}</span></div></div>},{key:'state',title:'وضعیت',render:x=><StatusBadge value={x.is_active?'active':'disabled'}/>},...(canManage?[{key:'actions',title:'عملیات',render:(x:AudioAd)=><div className="row-actions"><button className="icon-button" onClick={()=>{setEditing(x);setOpen(true)}} aria-label="ویرایش تبلیغ"><Pencil size={16}/></button><button className="icon-button icon-button--danger" onClick={()=>setDel({kind:'audio',id:x.id,title:x.title})} aria-label="حذف تبلیغ"><Trash2 size={16}/></button></div>}]:[])
 ]}/>{remote.data&&<Pagination count={remote.data.count} page={page} pageSize={20} onPage={setPage}/>}</>}</Card>{canManage&&open&&<AudioEditor open item={editing} onClose={()=>setOpen(false)} onSaved={saved=>{const snapshot=pageSnapshot(remote.data,saved.id);const isCreate=snapshot.index<0;const visible=!isCreate||page===1;const preferred=isCreate&&visible?[saved.id,...snapshot.order]:snapshot.order;remote.setData(current=>setPaginatedItem(current,saved,{visible,indexHint:isCreate?0:snapshot.index}));setEditing(null);setOpen(false);syncAudio(saved,{...snapshot,order:preferred},true,visible,'saved')}}/>}<Confirm open={Boolean(del)} title="حذف تبلیغ صوتی" text={`تبلیغ «${del?.title||''}» حذف شود؟`} confirmLabel="حذف" danger busy={busy} onClose={()=>setDel(null)} onConfirm={()=>void remove()}/></>
}

function AudioEditor({open,item,onClose,onSaved}:{open:boolean;item:AudioAd|null;onClose:()=>void;onSaved:(saved:AudioAd)=>void|Promise<void>}){
 const toast=useToast();const[busy,setBusy]=useState(false);const[title,setTitle]=useState(item?.title||'');const[titleEn,setTitleEn]=useState(item?.title_en||'');const[link,setLink]=useState(item?.navigate_link||'');const[active,setActive]=useState(item?.is_active??true);const[audio,setAudio]=useState<File|null>(null);const[cover,setCover]=useState<File|null>(null)
 async function submit(e:FormEvent){e.preventDefault();if(!item&&!audio){toast.show('فایل صوتی تبلیغ را انتخاب کنید.','error');return}setBusy(true);try{const f=new FormData();f.append('title',title);f.append('title_en',titleEn);f.append('navigate_link',link);f.append('is_active',String(active));if(audio)f.append('audio_upload',audio);if(cover)f.append('image_cover_upload',cover);const response=await api<AudioAd>(item?`/admin/ads/audio/${item.id}/`:'/admin/ads/audio/',{method:item?'PATCH':'POST',body:f});const saved:AudioAd={...response,title,title_en:titleEn,navigate_link:link,is_active:active};toast.show(item?'تبلیغ صوتی به‌روزرسانی شد.':'تبلیغ صوتی ایجاد شد.','success');await onSaved(saved)}catch(err){toast.show(errorMessageFa(err),'error')}finally{setBusy(false)}}
 return <Modal open={open} title={item?'ویرایش تبلیغ صوتی':'تبلیغ صوتی جدید'} onClose={onClose}><form className="form-grid" onSubmit={submit}><Field label="عنوان فارسی"><input value={title} onChange={e=>setTitle(e.target.value)} required/></Field><Field label="عنوان انگلیسی"><input dir="ltr" value={titleEn} onChange={e=>setTitleEn(e.target.value)} required/></Field><div className="form-grid__full"><Field label="لینک مقصد"><input dir="ltr" value={link} onChange={e=>setLink(e.target.value)} placeholder="نشانی مقصد"/></Field></div><Field label="فایل صوتی"><input type="file" accept="audio/*" onChange={e=>setAudio(e.target.files?.[0]||null)}/></Field><Field label="تصویر کاور"><input type="file" accept="image/*" onChange={e=>setCover(e.target.files?.[0]||null)}/></Field><label className="switch-row form-grid__full"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><span className="switch"/><span><strong>تبلیغ فعال باشد</strong></span></label><div className="dialog-actions form-grid__full"><button type="button" className="button button--ghost" onClick={onClose}>انصراف</button><button className="button button--primary" disabled={busy}>{busy?'در حال ذخیره…':'ذخیره تبلیغ'}</button></div></form></Modal>
}
