import { useEffect, useState, type ReactNode } from 'react'
import { NavLink, useNavigate } from 'react-router-dom'
import { BadgeDollarSign, CirclePlus, Disc3, LayoutDashboard, Layers3, LifeBuoy, ListMusic, LogOut, Menu, Music2, PanelsTopLeft, ShieldCheck, Tags, UserRoundCog, Users, WalletCards, X } from 'lucide-react'
import { useAuth } from '../lib/authContext'
import { canView,isOwnerAdmin,type ScreenKey } from '../lib/permissions'
const nav:Array<{to:string;label:string;icon:typeof LayoutDashboard;screen?:ScreenKey;adminOnly?:boolean}>=[
 {to:'/',label:'داشبورد',icon:LayoutDashboard,adminOnly:true},{to:'/users',label:'کاربران',icon:Users,screen:'users'},{to:'/artists',label:'هنرمندان',icon:ShieldCheck,screen:'artists'},{to:'/releases/add',label:'افزودن انتشار',icon:CirclePlus,screen:'release_add'},{to:'/releases',label:'بررسی انتشارها',icon:Music2,screen:'releases'},{to:'/songs',label:'آهنگ‌ها',icon:ListMusic,screen:'songs'},{to:'/albums',label:'آلبوم‌ها',icon:Disc3,screen:'albums'},{to:'/tags',label:'تگ‌ها',icon:Tags,screen:'tags'},{to:'/plans',label:'پلن و قیمت‌گذاری',icon:BadgeDollarSign,screen:'plans'},{to:'/finance',label:'مالی و تسویه',icon:WalletCards,screen:'finance'},{to:'/content',label:'محتوا و پیشنهادها',icon:PanelsTopLeft,screen:'content'},{to:'/playlists-sections',label:'پلی‌لیست‌ها و بخش‌ها',icon:Layers3,screen:'playlists'},{to:'/support',label:'پشتیبانی و گزارش‌ها',icon:LifeBuoy,screen:'support'},{to:'/employees',label:'کارمندان',icon:UserRoundCog,adminOnly:true},
]
export function AppShell({children}:{children:ReactNode}){const[drawer,setDrawer]=useState(false);const navigate=useNavigate();const{user,logout}=useAuth();const owner=isOwnerAdmin(user);const visibleNav=nav.filter(i=>i.adminOnly?owner:i.screen?canView(user,i.screen):true)
 useEffect(()=>{if(!drawer)return;const close=(e:KeyboardEvent)=>e.key==='Escape'&&setDrawer(false);document.addEventListener('keydown',close);document.body.classList.add('drawer-open');return()=>{document.removeEventListener('keydown',close);document.body.classList.remove('drawer-open')}},[drawer])
 const doLogout=async()=>{await logout();navigate('/login',{replace:true})}
 return <div className="app-shell">{drawer&&<button className="drawer-backdrop" aria-label="بستن منو" onClick={()=>setDrawer(false)}/>}<aside className={`sidebar ${drawer?'is-open':''}`}><div className="brand"><img src="/sedabox-logo.png" alt="نشان صداباکس"/><div><strong>صداباکس</strong><span>{owner?'پنل مدیریت':'پنل کارمند'}</span></div><button className="icon-button sidebar__close" onClick={()=>setDrawer(false)} aria-label="بستن منو"><X size={20}/></button></div><nav>{visibleNav.map(i=><NavLink key={i.to} to={i.to} end={i.to==='/'||i.to==='/releases'} className={({isActive})=>`nav-item ${isActive?'is-active':''}`} onClick={()=>setDrawer(false)}><i.icon size={19}/><span>{i.label}</span></NavLink>)}</nav><div className="sidebar__footer"><div className="admin-mini"><span className="admin-mini__avatar">{user?.first_name?.[0]||(owner?'م':'ک')}</span><div><strong>{[user?.first_name,user?.last_name].filter(Boolean).join(' ')||(owner?'مدیر سیستم':'کارمند')}</strong><span>{owner?'مدیر اصلی':user?.employee_role==='manager'?'مدیر':'سرپرست'} · {user?.phone_number}</span></div></div><button className="nav-item nav-item--button" onClick={doLogout}><LogOut size={19}/><span>خروج از حساب</span></button></div></aside><div className="app-main"><header className="mobile-topbar"><button className="icon-button" onClick={()=>setDrawer(true)} aria-label="باز کردن منو"><Menu size={22}/></button><div className="mobile-brand"><img src="/sedabox-logo.png" alt=""/><strong>{owner?'مدیریت صداباکس':'پنل کارمند صداباکس'}</strong></div></header><main className="content">{children}</main></div></div>}
